"""Supabase Cloud Database integration for StatementHub.

Provides persistent storage, daily statement deduplication,
and party name mappings sync.
"""

from __future__ import annotations

import hashlib
import os
import re
from typing import Any

import pandas as pd

try:
    from supabase import Client, create_client
except ImportError:
    Client = None
    create_client = None

try:
    import streamlit as st
except ImportError:
    st = None


SUPABASE_SCHEMA_SQL = """-- Run this in Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. Table for bank transactions (with automatic deduplication)
create table if not exists transactions (
    id bigint generated by default as identity primary key,
    fingerprint text unique not null,
    bank text not null,
    date text not null,
    description text not null,
    party_name text default '',
    amount numeric not null,
    type text not null,
    utr text default '',
    balance numeric,
    party_match_key text not null,
    source_file text default '',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Indexes for lightning fast searches
create index if not exists idx_transactions_utr on transactions(utr);
create index if not exists idx_transactions_date on transactions(date);
create index if not exists idx_transactions_fingerprint on transactions(fingerprint);
create index if not exists idx_transactions_match_key on transactions(party_match_key);

-- 2. Table for reusable party / vendor mappings
create table if not exists party_mappings (
    match_key text primary key,
    party_name text not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
"""


def clean_str(val: Any) -> str:
    if val is None or pd.isna(val):
        return ""
    return re.sub(r"\s+", " ", str(val)).strip()


def compute_transaction_fingerprint(row: dict[str, Any]) -> str:
    """Generate a stable fingerprint independent of the upload file name.

    Deduplicates overlapping daily statements while preserving legitimate
    identical amounts (via unique UTRs, closing balances, or timestamps).
    """
    amount = row.get("Amount")
    amount_str = f"{float(amount):.2f}" if amount is not None and not pd.isna(amount) else "0.00"
    balance = row.get("Balance")
    balance_str = f"{float(balance):.2f}" if balance is not None and not pd.isna(balance) else ""

    parts = [
        clean_str(row.get("Bank")),
        clean_str(row.get("Date")),
        amount_str,
        clean_str(row.get("Type")),
        clean_str(row.get("UTR / Reference")),
        clean_str(row.get("Description")),
        balance_str,
    ]
    return hashlib.sha256("|".join(parts).encode("utf-8")).hexdigest()


def get_supabase_client() -> Client | None:
    """Retrieve an authenticated Supabase client from Streamlit secrets or env vars."""
    if create_client is None:
        return None

    url = None
    key = None

    if st is not None and hasattr(st, "secrets") and "supabase" in st.secrets:
        url = st.secrets["supabase"].get("url")
        key = st.secrets["supabase"].get("key")

    if not url or not key:
        url = os.environ.get("SUPABASE_URL")
        key = os.environ.get("SUPABASE_KEY")

    if not url or not key:
        return None

    try:
        return create_client(url, key)
    except Exception:
        return None


def fetch_party_mappings(client: Client) -> dict[str, str]:
    """Fetch all reusable party mappings from Supabase."""
    try:
        response = client.table("party_mappings").select("match_key, party_name").execute()
        return {item["match_key"]: item["party_name"] for item in response.data}
    except Exception:
        return {}


def save_party_mapping(client: Client, match_key: str, party_name: str) -> bool:
    """Save or update a reusable party mapping and update existing matching transactions."""
    try:
        client.table("party_mappings").upsert({
            "match_key": match_key,
            "party_name": party_name,
        }).execute()

        # Update all matching transactions in Supabase
        client.table("transactions").update({
            "party_name": party_name,
        }).eq("party_match_key", match_key).execute()
        return True
    except Exception:
        return False


def delete_party_mapping(client: Client, match_key: str) -> bool:
    """Remove a party mapping and reset matching transactions."""
    try:
        client.table("party_mappings").delete().eq("match_key", match_key).execute()
        client.table("transactions").update({
            "party_name": "",
        }).eq("party_match_key", match_key).execute()
        return True
    except Exception:
        return False


def clear_all_party_mappings(client: Client) -> bool:
    """Clear all party mappings in Supabase."""
    try:
        client.table("party_mappings").delete().neq("match_key", "").execute()
        client.table("transactions").update({"party_name": ""}).neq("fingerprint", "").execute()
        return True
    except Exception:
        return False


def save_transaction_override(client: Client, fingerprint: str, party_name: str) -> bool:
    """Save an override for a single transaction in Supabase."""
    try:
        client.table("transactions").update({
            "party_name": party_name,
        }).eq("fingerprint", fingerprint).execute()
        return True
    except Exception:
        return False


def sync_transactions_with_dedup(client: Client, df: pd.DataFrame) -> tuple[int, int]:
    """Insert new transactions into Supabase, automatically skipping duplicates.

    Returns (new_inserted_count, duplicates_skipped_count).
    """
    if df.empty:
        return 0, 0

    records: list[dict[str, Any]] = []
    fingerprints: list[str] = []

    for _, row in df.iterrows():
        fp = row.get("fingerprint") or compute_transaction_fingerprint(row.to_dict())
        fingerprints.append(fp)
        records.append({
            "fingerprint": fp,
            "bank": clean_str(row.get("Bank")),
            "date": clean_str(row.get("Date")),
            "description": clean_str(row.get("Description")),
            "party_name": clean_str(row.get("Party Name")),
            "amount": float(row.get("Amount", 0)) if row.get("Amount") is not None and not pd.isna(row.get("Amount")) else 0.0,
            "type": clean_str(row.get("Type")),
            "utr": clean_str(row.get("UTR / Reference")),
            "balance": float(row.get("Balance")) if row.get("Balance") is not None and not pd.isna(row.get("Balance")) else None,
            "party_match_key": clean_str(row.get("Party match key")),
            "source_file": clean_str(row.get("Source file")),
        })

    # Query existing fingerprints in Supabase (in chunks of 200)
    existing_fps: set[str] = set()
    chunk_size = 200
    for i in range(0, len(fingerprints), chunk_size):
        chunk = fingerprints[i:i + chunk_size]
        try:
            res = client.table("transactions").select("fingerprint").in_("fingerprint", chunk).execute()
            for item in res.data:
                existing_fps.add(item["fingerprint"])
        except Exception:
            pass

    to_insert = [r for r in records if r["fingerprint"] not in existing_fps]
    skipped_count = len(records) - len(to_insert)

    if to_insert:
        # Insert in chunks of 100
        for i in range(0, len(to_insert), 100):
            sub_chunk = to_insert[i:i + 100]
            client.table("transactions").insert(sub_chunk).execute()

    return len(to_insert), skipped_count


def fetch_all_transactions(client: Client, limit: int = 50000) -> pd.DataFrame:
    """Fetch stored transactions from Supabase into a DataFrame using pagination."""
    try:
        all_data: list[dict[str, Any]] = []
        page_size = 1000
        start = 0

        while start < limit:
            end = min(start + page_size - 1, limit - 1)
            response = (
                client.table("transactions")
                .select("id, fingerprint, bank, date, description, party_name, amount, type, utr, balance, party_match_key, source_file")
                .order("id", desc=True)
                .range(start, end)
                .execute()
            )
            if not response.data:
                break
            all_data.extend(response.data)
            if len(response.data) < page_size:
                break
            start += page_size

        if not all_data:
            return pd.DataFrame()

        rows = []
        for r in all_data:
            rows.append({
                "Bank": r["bank"],
                "Date": r["date"],
                "Description": r["description"],
                "Party Name": r["party_name"] or "",
                "Amount": float(r["amount"]) if r["amount"] is not None else 0.0,
                "Type": r["type"],
                "UTR / Reference": r["utr"] or "",
                "Balance": float(r["balance"]) if r["balance"] is not None else None,
                "Party match key": r["party_match_key"] or "",
                "Source file": r["source_file"] or "",
                "Transaction key": r["fingerprint"],
                "fingerprint": r["fingerprint"],
                "Original columns": {},
            })

        df = pd.DataFrame(rows)
        ids = df["UTR / Reference"]
        df["Duplicate UTR"] = ids.ne("") & ids.duplicated(keep=False)
        return df
    except Exception:
        return pd.DataFrame()
